baseURL = "https://aegisonic.org/"
languageCode = "en-us"

title = "Aegisonic"
description= "An adaptive headset designed to reduce auditory overstimulation & distress in autism."

[menus]
    [[menus.main]]
        name = 'Gallery'
        url = '/gallery'
        weight = 1

[params]
    tagline = "Equitable acoustics"
    
    [params.hero]
        link = "/about"
        cta = "Learn more"

[module]
    [module.hugoVersion]
        extended = false
        min = "0.146.0"

[caches]
  [caches.images]
    dir = ':cacheDir/images'